//cgsi objects
var buildings = {
  0:"Administration Building",
  1:"Albin O. Kuhn Library",
  2:"Biological Sciences Building",
  3:"Meyerhoff Chemistry Building",
  4:"True Grit's",
  5:"Engineering Building",
  6:"Fine Arts Building",
  7:"Information Technology / Engineering Building",
  8:"Lecture Hall 1",
  9:"Math and Psychology Building",
  10:"Performing Arts and Humanitites Building",
  11:"Physics Building",
  12:"Public Policy Building",
  13:"Sherman Hall",
  14:"Janet and Walter Sondheim Hall",
  15:"Student Development and Success Center",
  16:"Tech 2 Building",
  17:"Technology Research Center",
  18:"Academic Services Building",
  19:"University Center",
  20:"The Commons",
};


var buildingstrings = [
"Administration Building",
"Albin O. Kuhn Library",
"Biological Sciences Building",
"Meyerhoff Chemistry Building",
"True Grit's",
"Engineering Building",
"Fine Arts Building",
"Information Technology / Engineering Building",
"Lecture Hall 1",
"Math and Psychology Building",
"Performing Arts and Humanitites Building",
"Physics Building",
"Public Policy Building",
"Sherman Hall",
"Janet and Walter Sondheim Hall",
"Student Development and Success Center",
"Tech 2 Building",
"Technology Research Center",
"Academic Services Building",
"University Center",
"The Commons",
];

var buildingstringshort = [
"AD",
"LIB",
"BIOL",
"MEYR",
"DH",
"ENGR",
"FA",
"ITE",
"LH1",
"MP",
"PAHB",
"PHYS",
"PUP",
"SHER",
"SOND",
"SDSC",
"TEC2",
"TRC",
"THAC",
"UC",
"COMM",
];